### ISSUE TITLE
Add blank node to charts for current day

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#101]
One way to fix the chart issues not displaying inactivity is to add one blank node for the current day, using the same values as the previous node. This blank node would not display any tooltip on hover, it is purely cosmetic, and would draw a flat line. 

Reference: I have not played this game mode in a few months, yet my graph shows a flat line indicating my rank stayed the same since I last played.

![image](https://github.com/osu-tournament-rating/otr-web/assets/38370573/4ba9d0a6-b76d-44ae-bb82-172d9b6e8247)

**Comment by AkinariHex** [comment]
This has been added.
