### ISSUE TITLE
Logging in should reset the user's cookies

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#122]
If a user has to login for some reason, their cookies should be reset. What happens now is the user may have outdated roles/permissions (i.e. not whitelisted) and in order for the cookies to update, they have to be cleared. Clearing the cookies when logging in could clear some frustration.

What do you think of this akinari?

**Comment by AkinariHex** [comment]
By logging each time I rewrite the cookies if they already exists
