### ISSUE TITLE
Remove API secrets

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-web#125]
The API no longer uses the values from `Auth.WebLoginAuthSecret` and `Auth.PrivilegedClientSecret` as of [#184](https://github.com/osu-tournament-rating/otr-api/pull/184) so they are safe to remove here as well

**Comment by myssto** [comment]
@AkinariHex

**Comment by hburn7** [comment]
I think this can be closed at this point right?

**Comment by AkinariHex** [comment]
Right now I only use the bearer token as authentication in all the requests that require the bearer token
