### ISSUE TITLE
Token expiration should be checked when submitting tournaments

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#134]
There was a case where a user tried to submit a tournament after being logged into the site for a long time. The user probably left the submissions page open for a very long time (likely long enough for the `accessToken` to expire). They then tried to submit a tournament and it failed.

Investigate behavior of refreshing the `accessToken` while saving tournament submission data so that the user does not have to resubmit.

**Comment by alixdotsh** [comment]
gonna try to take a shot at this later
