### ISSUE TITLE
New ruleset selector behavior

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#178]
# Ruleset Selector Behavior Change

Depends on:

- [ ] #136 

As discussed with starlight, the ruleset selector will change to have the following behavior:

- If a user changes the ruleset to something other than their default (as described in #136), they enter into an "exploratory" mode.
- If the user is in this exploratory mode, the ruleset should revert to the user's default browsing setting whenever they navigate away from the page they are currently viewing.
- If the user refreshes the same page while in the exploratory mode, they should remain in an exploratory mode. The ruleset should only ever change without user intervention when they load a new page.

**Comment by myssto** [comment]
We collectively decided to move on from this idea with the selector in the navbar feeling confusing more than anything
