### ISSUE TITLE
Remove 0.0 decay from all profiles

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#187]
There is a '0.0' decay tooltip on all charts that should not be there. This should be removed.

![image](https://github.com/osu-tournament-rating/otr-web/assets/38370573/0e5d5123-feef-4f13-99b3-b001cf8ffcdb)

**Comment by AkinariHex** [comment]
This was added to show a better graph and not having spikes on the line

**Comment by hburn7** [comment]
Alright, in this case, the chart should end at the last match the user has played. For example, if my last rating change is March 1, 2023, the chart should end at March 1, 2023. 

On chess.com, you can see [here](https://www.chess.com/stats/live/bullet/stageosu/365) that my last played bullet game is April 1, 2024. The chart ends there.

**Comment by hburn7** [comment]
![image](https://github.com/osu-tournament-rating/otr-web/assets/38370573/c5221e24-6644-486a-8ddf-65c78c8f39d6)
This is how rating updates should appear over time as well. The date on the bottom is evenly spread out, and the rating change looks like steps/stairs when a sudden change occurs after a period of inactivity. A smooth curve should be for consistent play.

**Comment by hburn7** [comment]
> ![image](https://private-user-images.githubusercontent.com/38370573/332499759-c5221e24-6644-486a-8ddf-65c78c8f39d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDgxMzgsIm5iZiI6MTcxNjMwNzgzOCwicGF0aCI6Ii8zODM3MDU3My8zMzI0OTk3NTktYzUyMjFlMjQtNjY0NC00ODZhLThkZGYtNjVjNzhjOGYzOWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE2MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZWIzOGJjNzc1N2M0OTNjNDRlMGI0MzRkY2FlNjhhNjIwNzY5ZGRmMzZkMGVjMDllNDYyM2M0Y2RkMjU0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7NLp-KT6wkn8cnUIqNWOWgBRVPcuaUGMuc_9Ey1U2Y) This is how rating updates should appear over time as well. The date on the bottom is evenly spread out, and the rating change looks like steps/stairs when a sudden change occurs after a period of inactivity. A smooth curve should be for consistent play.

@AkinariHex For now though, I'm completely fine with anything *so long as* the date on the x-axis is distributed evenly.
